os: linux
dist: focal
language: cpp
compiler:
  - gcc
  - clang

install:
  - pip install --user conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add artifactory https://api.bintray.com/conan/craiganv/cpp-skeleton-repo
  - conan remote list

script:
  - cd libskeleton/
  - mkdir build && cd build/
  - conan install .. --build missing
  - cmake .. -DUSE_CONAN_PACKAGE=True -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
  - cmake --build . --parallel 2
  - ctest --parallel 2
  - cmake --install .
  - ls -al
  - cat cmake_install.cmake
  - sudo make install
  - cpack
  - cd ../../consumer/
  - mkdir build && cd build/
  - conan remove -f "*" # ensure consumer is NOT built against Conan libs
  - conan search
  - sudo apt-get -y install libboost-all-dev libgtest-dev libbz2-dev
  - cat /usr/local/lib/cmake/Skeleton/*
  - cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
  - cmake --build . --parallel 2
  - ./skeletonconsumer
