os: linux
dist: focal
language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-focal-10
    packages:
      - clang-10

install:
    - pip install --user conan
    - conan --version
    - cmake --version
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan remote add artifactory https://api.bintray.com/conan/craiganv/cpp-skeleton-repo
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - conan remote list

script:
  - cd libskeleton/
  - mkdir build && cd build/
  - conan install ../conan/ --build=missing
  - conan user -p 27a043aba804df92adced3df42da32fedd7abc6e -r artifactory craiganv
  - conan upload "*" -r artifactory --all --confirm
  - cmake .. -DUSE_CONAN_PACKAGE=True -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
  - cmake --build . --parallel 2
  - ctest --parallel 2
  - cmake --install .
  - ls -al
  - cat cmake_install.cmake
  - cpack
  - sudo make install
  - cd ../../consumer/
  - mkdir build && cd build/
  - conan remove -f "*"
  - conan search
  - sudo apt-get -y install libboost-all-dev libbz2-dev libpoco-dev libopencv-dev
  - cat /usr/local/lib/cmake/Skeleton/*
  - cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
  - cmake --build . --parallel 2
  - ./skeletonconsumer
