dist: focal
sudo: true
language: cpp
compiler:
  - gcc

install:
  - pip install --user conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - mkdir build && cd build
  - conan install .. --build missing
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . -- -j2
  - ctest -j2
