os: linux
dist: focal
language: cpp
compiler:
  - gcc
  - clang

install:
  - pip install --user conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - cd libskeleton/
  - mkdir build && cd build/
  - conan install ../.. --build missing
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . -- -j2
  - ctest -j2
  - cmake --install .
  - cd ../../consumer/
  - mkdir build && cd build/
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . -- -j2
