version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan remote add artifactory https://api.bintray.com/conan/craiganv/cpp-skeleton-repo
  - cmd: conan remote list
  - cmd: conan --version
  - cmd: cmake --version

build_script:
  - cmd: cd libskeleton
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. --build missing
  - cmd: cmake .. -DUSE_CONAN_PACKAGE=True -G "Visual Studio 16"
  - cmd: cmake --build . --config Release --parallel 2
  - cmd: ctest --parallel 2
  - cmd: cmake --install .
  - cmd: cpack
  - cmd: cd ../../consumer/
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 16"
  - cmd: cmake --build . --config Release --parallel 2

test_script:
  - cmd: cd Release
  - cmd: skeletonconsumer
